// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mznnbuqypfgqdopupzyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16bm5idXF5cGZncWRvcHVwenluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MDQwNTIsImV4cCI6MjA3NTA4MDA1Mn0.tSVKzsy_OR7sLVMZhh7LE7POWJ5A0JwTxKD8ZLWSpMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
